

service: freq-crunch-api
useDotenv: true
frameworkVersion: '2'

plugins:
  - serverless-offline



provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 15
  endpointType: regional
  


functions: 
  get-all:
    handler: api/get-all.handler
    description: GET all show events
    events:
      - http:
          path: shows
          method: get
          cors:
            origin: '*'