

service: freq-crunch-api
frameworkVersion: '2'
variablesResolutionMode: 20210219

custom:
  # Do this if you only want to load env vars into the Serverless environment
  # This will make env vars available here and in any Serverless plugins
  dotenvVars: ${file(config.js)}

plugins:
  - serverless-offline


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 15
  endpointType: regional
  
functions: 
  get-all:
    handler: api/get-all.handler
    description: GET all show events
    environment:
      DB_CONNECT_STRING: ${self:custom.dotenvVars.DB_CONNECT_STRING}
    events:
      - http:
          path: shows
          method: get
          cors:
            origin: '*'
  count-all:
      handler: api/count-all.handler
      description: GET number of records in database
      environment:
        DB_CONNECT_STRING: ${self:custom.dotenvVars.DB_CONNECT_STRING}
      events:
        - http:
            path: get-count
            method: get
            cors:
              origin: '*'
  next-week:
      handler: api/next-week.handler
      description: GET number of records in database
      environment:
        DB_CONNECT_STRING: ${self:custom.dotenvVars.DB_CONNECT_STRING}
      events:
        - http:
            path: get-next-week
            method: get
            cors:
              origin: '*'
  count-next-week:
      handler: api/count-next-week.handler
      description: GET number of records in database
      environment:
        DB_CONNECT_STRING: ${self:custom.dotenvVars.DB_CONNECT_STRING}
      events:
        - http:
            path: get-count-next-week
            method: get
            cors:
              origin: '*'
  count-venues:
    handler: api/count-venues.handler
    description: GET number of records in database
    environment:
        DB_CONNECT_STRING: ${self:custom.dotenvVars.DB_CONNECT_STRING}
    events:
      - http:
          path: get-count-venues
          method: get
          cors:
            origin: '*'