

service: freq-crunch-api
useDotenv: true
frameworkVersion: '2'

plugins:
  - serverless-offline



provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 15
  endpointType: regional
  


functions: 
  get-all:
    handler: api/get-all.handler
    description: GET all show events
    events:
      - http:
          path: shows
          method: get
          cors:
            origin: '*'
  count-all:
      handler: api/count-all.handler
      description: GET number of records in database
      events:
        - http:
            path: get-count
            method: get
            cors:
              origin: '*'
  next-week:
      handler: api/next-week.handler
      description: GET number of records in database
      events:
        - http:
            path: get-next-week
            method: get
            cors:
              origin: '*'
  count-next-week:
      handler: api/count-next-week.handler
      description: GET number of records in database
      events:
        - http:
            path: get-count-next-week
            method: get
            cors:
              origin: '*'
  count-venues:
    handler: api/count-venues.handler
    description: GET number of records in database
    events:
      - http:
          path: get-count-venues
          method: get
          cors:
            origin: '*'